import * as resources from "../controllers/adminResourcesController.ts";
import * as identity from "../controllers/identityController.ts";
import { listCategories, updateItem, deleteItem } from "../controllers/itemsController.ts";
import { updateRentalStatus } from "../controllers/rentalsController.ts";
import { refundPayment } from "../controllers/paymentsController.ts";
import { updateItemUpload } from "../middlewares/upload.ts";
import { verifyUploads } from "../middlewares/privateUpload.ts";
import { Router } from "express";
import { correctUserCpf, deleteUser, listAdminItems, listAdminRentals, listUsers, metrics, updateUserStatus } from "../controllers/adminController.ts";
import { requireAdmin } from "../middlewares/auth.ts";
const router = Router();
router.use(requireAdmin);
router.get("/metricas", metrics);
router.get("/usuarios", listUsers);
router.patch("/usuarios/:id/cpf", correctUserCpf);
router.patch("/usuarios/:id/status", updateUserStatus);
router.delete("/usuarios/:id", deleteUser);
router.get("/objetos", listAdminItems);
router.get("/alugueis", listAdminRentals);
router.patch("/objetos/:id", updateItemUpload, verifyUploads, updateItem);
router.delete("/objetos/:id", deleteItem);
router.patch("/alugueis/:id", updateRentalStatus);
router.get("/conciliacoes",resources.adminReconciliations);
router.get("/webhooks-pendentes",resources.adminPendingWebhooks);
router.get("/pagamentos", resources.adminPayments);
router.post("/pagamentos/:id/estornar", refundPayment);
router.get("/verificacoes", identity.listIdentities);
router.patch("/verificacoes/:id", identity.reviewIdentity);
router.get("/verificacoes/:id/documentos/:tipo", identity.identityDocument);
router.get("/suporte", resources.listCases("suporte"));
router.patch("/suporte/:id", resources.reviewCase("suporte"));
router.get("/denuncias", resources.listCases("denuncia"));
router.patch("/denuncias/:id", resources.reviewCase("denuncia"));
router.get("/sinistros", resources.listCases("sinistro"));
router.patch("/sinistros/:id", resources.reviewCase("sinistro"));
router.get("/avaliacoes", resources.adminReviews);
router.delete("/avaliacoes/:id", resources.removeReview);
router.get("/categorias", listCategories);
router.post("/categorias", resources.saveCategory);
router.patch("/categorias/:id", resources.saveCategory);
router.delete("/categorias/:id", resources.deleteCategory);
export default router;
