import prisma from "../config/database.ts";
import { Router } from "express";
import { deleteNotification, listNotifications, markNotification } from "../controllers/notificationsController.ts";
import { requireAuth } from "../middlewares/auth.ts";
const router = Router();
router.use(requireAuth);
router.get("/", listNotifications);
router.patch("/ler-todas", async (req, res) => { await prisma.notificacoes.updateMany({ where: { usuario_id: req.user!.id }, data: { lida: true } }); res.json({ success: true }); });
router.post("/ler-todas", async (req, res) => { await prisma.notificacoes.updateMany({ where: { usuario_id: req.user!.id }, data: { lida: true } }); res.json({ success: true }); });
router.patch("/:id", markNotification);
router.delete("/:id", deleteNotification);
export default router;
