// Expõe cadastro, perfil, identidade, endereço e preferências; rotas privadas exigem sessão.
import * as settings from "../controllers/accountSettingsController.ts";
import * as addresses from "../controllers/addressesController.ts";
import * as identity from "../controllers/identityController.ts";
import { identityUpload } from "../middlewares/privateUpload.ts";
import { verifyUploads } from "../middlewares/privateUpload.ts";
import { Router } from "express";
import { register } from "../controllers/authController.ts";
import { ownProfile, publicProfile, updateProfile, uploadAvatar } from "../controllers/usersController.ts";
import { requireAuth } from "../middlewares/auth.ts";
import { avatarUpload } from "../middlewares/upload.ts";
import { rateLimit } from "../middlewares/rateLimit.ts";
import { getMyRentalBlock } from "../controllers/rentalsController.ts";
import { listReceivedReviews } from "../controllers/reviewsController.ts";
const router = Router();
router.post("/", rateLimit({ windowMs: 60 * 60_000, max: 10, identity: "ip", scope: "register" }), register);
router.get("/me", requireAuth, ownProfile);
router.get("/me/bloqueio", requireAuth, getMyRentalBlock);
router.patch("/me", requireAuth, updateProfile);
router.get("/perfil", requireAuth, ownProfile);
router.put("/perfil", requireAuth, updateProfile);
router.patch("/perfil", requireAuth, updateProfile);
router.post("/avatar", requireAuth, avatarUpload, verifyUploads, uploadAvatar);
router.delete("/avatar", requireAuth, settings.deleteAvatar);
router.post("/me/desativar", requireAuth, settings.deactivateAccount);
router.delete("/me", requireAuth, settings.closeAccount);
router.get("/me/exportar", requireAuth, settings.exportAccount);
router.put("/senha", requireAuth, settings.changePassword);
router.put("/telefone", requireAuth, settings.changePhone);
router.put("/email", requireAuth, settings.changeEmail);
router.get("/email/confirmar", settings.confirmEmail);
router.post("/email/confirmar", settings.confirmEmail);
router.get("/preferencias-notificacao", requireAuth, settings.preferences("preferencias"));
router.put("/preferencias-notificacao", requireAuth, settings.preferences("preferencias"));
router.get("/privacidade", requireAuth, settings.preferences("privacidade"));
router.put("/privacidade", requireAuth, settings.preferences("privacidade"));
router.get("/me/verificacao", requireAuth, identity.identityStatus);
router.post("/verificacao", requireAuth, identityUpload, verifyUploads, identity.submitIdentity);
router.get("/me/enderecos", requireAuth, addresses.listAddresses);
router.get("/me/enderecos/:id", requireAuth, addresses.getAddress);
router.post("/me/enderecos", requireAuth, addresses.saveAddress);
router.patch("/me/enderecos/:id", requireAuth, addresses.saveAddress);
router.put("/me/enderecos/:id", requireAuth, addresses.saveAddress);
router.delete("/me/enderecos/:id", requireAuth, addresses.removeAddress);
router.get("/:id/avaliacoes-recebidas", listReceivedReviews);
router.get("/:id/avaliacoes-recebidas-locatario", listReceivedReviews);
router.get("/:id", publicProfile);
export default router;
