// Usa um provedor simulado e banco real para verificar cobranças, webhooks, falhas e repetição segura.
import assert from "node:assert/strict";
import test from "node:test";
import crypto from "node:crypto";
import { AsyncLocalStorage } from "node:async_hooks";
import type { AddressInfo } from "node:net";
const database=process.env.TEST_DATABASE_URL;
if(!database)throw new Error("TEST_DATABASE_URL é obrigatório para test:financial");
if(!new URL(database).pathname.startsWith("/vizin_contract_test_"))throw new Error("Banco de teste isolado obrigatório");process.env.DATABASE_URL=database;process.env.VIZIN_NO_LISTEN="true";process.env.NODE_ENV="dev";process.env.PAYMENT_MODE="demo";process.env.JWT_KEY="vizin-test-secret-with-at-least-32-characters";
function cpf(){let s=String(crypto.randomInt(100000000,999999999));for(const n of[9,10])s+=String(([...s].reduce((a,d,i)=>a+Number(d)*(n+1-i),0)*10%11)%10);return s;}
test("contrato financeiro → Mercado Pago fake → webhook → PostgreSQL",async t=>{
 const {default:app}=await import("../../app.ts"),{default:prisma}=await import("../../app/config/database.ts"),{default:env}=await import("../../app/config/env.ts"),{default:jwt}=await import("jsonwebtoken");
 const transactionContext=new AsyncLocalStorage<boolean>(),originalTransaction=prisma.$transaction.bind(prisma);
 (prisma as any).$transaction=(operation:any,...options:any[])=>typeof operation==="function"?(originalTransaction as any)((tx:any)=>transactionContext.run(true,()=>operation(tx)),...options):(originalTransaction as any)(operation,...options);
 const previousFetch=globalThis.fetch,previousMode=env.PAYMENT_MODE;
 const oldEnv={MP_ACCESS_TOKEN:process.env.MP_ACCESS_TOKEN,MP_WEBHOOK_SECRET:process.env.MP_WEBHOOK_SECRET,MULTA_VALOR_DIA:process.env.MULTA_VALOR_DIA};
 env.PAYMENT_MODE="gateway";process.env.MP_ACCESS_TOKEN="fake-access-token";process.env.MP_WEBHOOK_SECRET="fake-webhook-secret";delete process.env.MULTA_VALOR_DIA;
 const customers=new Map<string,any>(),cards=new Map<string,any>(),payments=new Map<string,any>(),idem=new Map<string,string>();
 let customerCreates=0,paymentCreates=0,cancels=0,refundCalls=0,refundPending=false,earlyWebhook=false,autoCardWebhook=true,loseCreationResponse=false,loseCustomerResponse=false,loseCardResponse=false,pixResponseMissing="",customerSearchExtra:any[]=[],externalPause:Promise<void>|null=null,seq=Date.now()*1000;
 const server=app.listen(0,"127.0.0.1");await new Promise<void>(resolve=>server.once("listening",resolve));const base=`http://127.0.0.1:${(server.address() as AddressInfo).port}/api`;
 t.after(async()=>{globalThis.fetch=previousFetch;(prisma as any).$transaction=originalTransaction;env.PAYMENT_MODE=previousMode;for(const[k,v]of Object.entries(oldEnv)){if(v===undefined)delete process.env[k];else process.env[k]=v;}await new Promise<void>((resolve,reject)=>server.close(e=>e?reject(e):resolve()));await prisma.$disconnect();});
 const owner=await prisma.usuarios.create({data:{nome:"MP dono",cpf:cpf(),email:`mp-owner-${crypto.randomUUID()}@test.local`,senha_hash:"not-used"}}),renter=await prisma.usuarios.create({data:{nome:"MP pagador",cpf:cpf(),email:`mp-renter-${crypto.randomUUID()}@test.local`,senha_hash:"not-used"}}),other=await prisma.usuarios.create({data:{nome:"MP terceiro",cpf:cpf(),email:`mp-other-${crypto.randomUUID()}@test.local`,senha_hash:"not-used"}});
 const bearer=(u:any)=>jwt.sign({id:u.id,email:u.email,tipo:u.tipo,tokenVersion:u.token_version},env.JWT_KEY);
 async function api(path:string,method="GET",body?:unknown,user=renter,key?:string){const headers:Record<string,string>={Authorization:`Bearer ${bearer(user)}`};if(body!==undefined)headers["Content-Type"]="application/json";if(key)headers["Idempotency-Key"]=key;const response=await fetch(base+path,{method,headers,...(body===undefined?{}:{body:JSON.stringify(body)})});return{status:response.status,data:response.status===204?null:await response.json() as any};}
 async function webhook(ref:string,event=String(++seq),valid=true,timestamp=Math.floor(Date.now()/1000)){const request=`req-${event}`,ts=String(timestamp),hash=crypto.createHmac("sha256","fake-webhook-secret").update(`id:${ref};request-id:${request};ts:${ts};`).digest("hex");const response=await fetch(`${base}/pagamentos/webhook?data.id=${ref}`,{method:"POST",headers:{"Content-Type":"application/json","x-request-id":request,"x-signature":`ts=${ts},v1=${valid?hash:"0".repeat(64)}`},body:JSON.stringify({id:event,type:"payment",data:{id:ref}})});return{status:response.status,data:response.status===204?null:await response.json() as any};}
 globalThis.fetch=async(input,init)=>{
  if(!String(input).startsWith("https://api.mercadopago.com/"))return previousFetch(input,init);
  const url=new URL(String(input)),path=url.pathname,method=init?.method ?? "GET",headers=init?.headers as Record<string,string>,body=init?.body?JSON.parse(String(init.body)):{};
  assert.equal(transactionContext.getStore(),undefined,`HTTP externo ${method} ${path} ocorreu dentro da transação Prisma`);
  assert.equal(headers.Authorization,"Bearer fake-access-token");
  const json=(value:any,status=200)=>new Response(JSON.stringify(value),{status,headers:{"Content-Type":"application/json"}});
  if(path==="/v1/customers/search")return json({results:[...customers.values(),...customerSearchExtra].filter(c=>c.email===url.searchParams.get("email"))});
  const customerPath=/^\/v1\/customers\/([^/]+)$/.exec(path);
  if(customerPath && method==="GET")return json(customers.get(customerPath[1]!) ?? customerSearchExtra.find(c=>c.id===customerPath[1]),customers.has(customerPath[1]!) || customerSearchExtra.some(c=>c.id===customerPath[1])?200:404);
  if(path==="/v1/customers" && method==="POST"){customerCreates++;const c={...body,id:`customer-${++seq}`};customers.set(c.id,c);if(loseCustomerResponse){loseCustomerResponse=false;throw new Error("Customer criado; resposta perdida");}return json(c,201);}
  const cardPath=/^\/v1\/customers\/([^/]+)\/cards(?:\/([^/]+))?$/.exec(path);
  if(cardPath){if(method==="POST"){const c={id:String(++seq),customer_id:cardPath[1],last_four_digits:"4242",expiration_month:12,expiration_year:2029,payment_method:{id:"visa"}};cards.set(c.id,c);if(loseCardResponse){loseCardResponse=false;throw new Error("Cartão criado; resposta perdida");}return json(c,201);}if(method==="DELETE"){cards.delete(cardPath[2]!);return new Response(null,{status:204});}}
  if(path==="/v1/payments/search")return json({results:[...payments.values()].filter(p=>p.external_reference===url.searchParams.get("external_reference"))});
  if(path==="/v1/payments" && method==="POST") {
   if(externalPause)await externalPause;
   const key=headers["X-Idempotency-Key"]!;assert.match(key,/^[a-f0-9]{64}$/);
   if(idem.has(key))return json(payments.get(idem.get(key)!));
   assert.equal(body.installments ?? 1,1);assert.ok(!("cvv"in body));
   if(body.payment_method_id==="pix"){assert.equal(body.payer.email,renter.email);assert.equal(body.payer.identification.number,renter.cpf);}
   paymentCreates++;const id=String(++seq),p={id,status:body.token==="rejected-token"?"rejected":body.payment_method_id==="pix"?"pending":"approved",currency_id:"BRL",transaction_amount:body.transaction_amount,external_reference:body.external_reference,metadata:body.metadata,date_of_expiration:body.date_of_expiration,card:body.payer.type==="customer"?{id:cardA}:undefined,point_of_interaction:{transaction_data:{qr_code:`PIX-real-${id}`,qr_code_base64:"aW1hZ2U="}}};if(body.token==="challenge-token"){p.status="in_process";(p as any).three_ds_info={external_resource_url:"https://issuer.test/challenge",creq:"challenge-request"};}
   if(pixResponseMissing==="qr")delete (p.point_of_interaction.transaction_data as any).qr_code_base64;
   if(pixResponseMissing==="code")delete (p.point_of_interaction.transaction_data as any).qr_code;
   if(pixResponseMissing==="expiration")delete (p as any).date_of_expiration;
   if(pixResponseMissing==="partial"){delete (p.point_of_interaction as any).transaction_data;delete (p as any).date_of_expiration;}
   pixResponseMissing="";
   payments.set(id,p);idem.set(key,id);
   if(earlyWebhook || (autoCardWebhook && p.status==="approved")){earlyWebhook=false;assert.equal((await webhook(id)).status,202);}
   if(loseCreationResponse){loseCreationResponse=false;throw new Error("Fake network timeout after successful creation");}
   return json(p,201);
  }
  const paymentPath=/^\/v1\/payments\/([^/]+)(\/refunds)?$/.exec(path);
  if(paymentPath){const p=payments.get(paymentPath[1]!);if(!p)return json({},404);if(paymentPath[2]){refundCalls++;if(externalPause)await externalPause;if(!refundPending)p.status="refunded";return json({id:String(++seq),status:refundPending?"pending":"approved"});}if(method==="PUT"){cancels++;if(externalPause)await externalPause;p.status="cancelled";}return json(p);}
  throw new Error(`Unexpected MP endpoint ${method} ${path}`);
 };
 const start=new Date(new Date(Date.now()+3*86400000).toISOString().slice(0,10)),end=new Date(start.getTime()+3*86400000);
 async function rental(overrides:Record<string,any>={}){const item=await prisma.itens.create({data:{usuario_id:owner.id,titulo:"Furadeira Bosch",preco_por_dia:35,valor_mercado:1000,fotos_item:{create:{url:"/uploads/items/test.png",principal:true}}}});return prisma.alugueis.create({data:{item_id:item.id,locador_id:owner.id,locatario_id:renter.id,data_inicio:start,data_fim:end,preco_dia_contratado:35,valor_total:105,status:"aprovado",pagamento_ate:new Date(Date.now()+86400000),...overrides}});}
 const charge=(id:string,body:any={metodo:"pix"},key:string=crypto.randomUUID())=>api(`/solicitacoes/${id}/pagamentos`,"POST",body,renter,key);
 let cardA="",cardB="";
 await t.test("listar cartões é autenticado e retorna array",async()=>{assert.deepEqual((await api("/cartoes")).data,[]);});
 await t.test("adicionar cartão cria customer e só retorna dados seguros",async()=>{const r=await api("/cartoes","POST",{token_cartao:"save-token"});assert.equal(r.status,201);cardA=r.data.id;assert.deepEqual(Object.keys(r.data).sort(),["id","bandeira","ultimos_digitos","validade","padrao"].sort());assert.equal(r.data.ultimos_digitos,"4242");});
 await t.test("primeiro cartão vira padrão",async()=>{assert.equal((await api("/cartoes")).data[0].padrao,true);});
 await t.test("customer não duplica em requests simultâneos",async()=>{const results=await Promise.all([api("/cartoes","POST",{token_cartao:"save-two"}),api("/cartoes","POST",{token_cartao:"save-three"})]);assert.ok(results.every(r=>r.status===201));cardB=results[0]!.data.id;assert.equal(customerCreates,1);assert.ok((await prisma.usuarios.findUniqueOrThrow({where:{id:renter.id}})).mercado_pago_customer_id);
  const firstConcurrent=await Promise.all([api("/cartoes","POST",{token_cartao:"other-one"},other),api("/cartoes","POST",{token_cartao:"other-two"},other)]);assert.ok(firstConcurrent.every(r=>r.status===201),JSON.stringify(firstConcurrent));assert.equal(customerCreates,2);assert.equal((await api("/cartoes","GET",undefined,other)).data.filter((c:any)=>c.padrao).length,1);});
 await t.test("customer sem marcador ou de outro usuário nunca é vinculado",async()=>{for(const description of [undefined,`vizin:${owner.id}`]){const user=await prisma.usuarios.create({data:{nome:"Customer isolado",cpf:cpf(),email:`customer-${crypto.randomUUID()}@test.local`,senha_hash:"not-used"}});customerSearchExtra=[{id:`foreign-${++seq}`,email:user.email,description}];const created=await api("/cartoes","POST",{token_cartao:`customer-${seq}`},user);assert.equal(created.status,201,JSON.stringify(created.data));const linked=(await prisma.usuarios.findUniqueOrThrow({where:{id:user.id}})).mercado_pago_customer_id;assert.ok(linked && linked!==customerSearchExtra[0].id);assert.equal(customers.get(linked)?.description,`vizin:${user.id}`);}customerSearchExtra=[];});
 await t.test("customer marcado corretamente é recuperado sem criar outro",async()=>{const user=await prisma.usuarios.create({data:{nome:"Customer recuperado",cpf:cpf(),email:`customer-${crypto.randomUUID()}@test.local`,senha_hash:"not-used"}});customerSearchExtra=[{id:`owned-${++seq}`,email:user.email,description:`vizin:${user.id}`}];const before=customerCreates;assert.equal((await api("/cartoes","POST",{token_cartao:`owned-${seq}`},user)).status,201);assert.equal((await prisma.usuarios.findUniqueOrThrow({where:{id:user.id}})).mercado_pago_customer_id,customerSearchExtra[0].id);assert.equal(customerCreates,before);customerSearchExtra=[];});
 await t.test("customer antigo persistido sem marcador é bloqueado",async()=>{const user=await prisma.usuarios.create({data:{nome:"Customer legado",cpf:cpf(),email:`customer-${crypto.randomUUID()}@test.local`,senha_hash:"not-used",mercado_pago_customer_id:`foreign-${++seq}`}});customerSearchExtra=[{id:`foreign-${seq}`,email:user.email}];const response=await api("/cartoes","POST",{token_cartao:"legacy-unsafe"},user);assert.equal(response.status,409);assert.equal(response.data.codigo,"customer_conflitante");customerSearchExtra=[];});
 await t.test("customer criado com resposta perdida é recuperado pelo marcador",async()=>{const user=await prisma.usuarios.create({data:{nome:"Customer recuperável",cpf:cpf(),email:`customer-${crypto.randomUUID()}@test.local`,senha_hash:"not-used"}});const before=customerCreates;loseCustomerResponse=true;const lost=await api("/cartoes","POST",{token_cartao:"customer-timeout"},user);assert.equal(lost.status,502);assert.equal((await prisma.operacoes_gateway.findUniqueOrThrow({where:{chave:`customer:${user.id}`}})).estado,"falhou");assert.equal((await prisma.usuarios.findUniqueOrThrow({where:{id:user.id}})).mercado_pago_customer_id,null);const recovered=await api("/cartoes","POST",{token_cartao:"customer-timeout"},user);assert.equal(recovered.status,201,JSON.stringify(recovered.data));assert.equal(customerCreates,before+1);assert.equal((await prisma.operacoes_gateway.findUniqueOrThrow({where:{chave:`customer:${user.id}`}})).estado,"concluida");});
 await t.test("cartão criado com resposta perdida exige conciliação e recupera a referência",async()=>{const user=await prisma.usuarios.create({data:{nome:"Cartão recuperável",cpf:cpf(),email:`card-${crypto.randomUUID()}@test.local`,senha_hash:"not-used"}}),token="card-timeout",digest=crypto.createHash("sha256").update(token).digest("hex"),key=`card:add:${user.id}:${digest}`;loseCardResponse=true;const before=cards.size;const lost=await api("/cartoes","POST",{token_cartao:token},user);assert.equal(lost.status,502);assert.equal(cards.size,before+1);const operation=await prisma.operacoes_gateway.findUniqueOrThrow({where:{chave:key}});assert.equal(operation.estado,"conciliacao");assert.equal(operation.referencia,null);const retry=await api("/cartoes","POST",{token_cartao:token},user);assert.equal(retry.status,409);assert.equal(retry.data.codigo,"conciliacao_pendente");assert.equal(cards.size,before+1);const remote=[...cards.values()].find(c=>c.customer_id===(operation.dados as any).customer_id && ![...cards.keys()].slice(0,before).includes(c.id));assert.ok(remote);await prisma.operacoes_gateway.update({where:{chave:key},data:{referencia:remote.id,dados:{id:remote.id,ultimos_digitos:"4242",validade:"12/29",payment_method_id:"visa",bandeira:"Visa"}}});const recovered=await api("/cartoes","POST",{token_cartao:token},user);assert.equal(recovered.status,201,JSON.stringify(recovered.data));assert.equal(recovered.data.id,remote.id);assert.equal(cards.size,before+1);assert.equal((await prisma.operacoes_gateway.findUniqueOrThrow({where:{chave:key}})).estado,"concluida");});
 await t.test("mudar padrão mantém exatamente um padrão",async()=>{assert.equal((await api(`/cartoes/${cardB}/padrao`,"PATCH")).status,200);const list=(await api("/cartoes")).data;assert.equal(list.filter((c:any)=>c.padrao).length,1);assert.equal(list.find((c:any)=>c.padrao).id,cardB);});
 await t.test("cartões de outro usuário são inacessíveis",async()=>{assert.ok((await api("/cartoes","GET",undefined,other)).data.every((c:any)=>c.id!==cardA && c.id!==cardB));assert.equal((await api(`/cartoes/${cardB}/padrao`,"PATCH",undefined,other)).status,404);assert.equal((await api(`/cartoes/${cardB}`,"DELETE",undefined,other)).status,404);});
 await t.test("excluir padrão promove outro e remove no Mercado Pago",async()=>{assert.equal((await api(`/cartoes/${cardB}`,"DELETE")).status,204);assert.equal(cards.has(cardB),false);assert.equal((await api("/cartoes")).data.filter((c:any)=>c.padrao).length,1);const all=(await api("/cartoes")).data;for(const c of all)if(c.id!==cardA)assert.equal((await api(`/cartoes/${c.id}`,"DELETE")).status,204);});
 await t.test("somente cartão efetivamente associado fica em uso",async()=>{const r=await rental(),payment=await charge(r.id,{metodo:"cartao",token_cartao:"approved-token",cartao_id:cardA});assert.equal(payment.status,200);const response=await api(`/cartoes/${cardA}`,"DELETE");assert.equal(response.status,409);assert.equal(response.data.codigo,"cartao_em_uso");assert.equal((await prisma.pagamentos.findUniqueOrThrow({where:{id:payment.data.pagamento_id}})).cartao_id,cardA);});
 await t.test("resumo calcula 105 + 3.50 e prazo oficial",async()=>{const r=await rental(),summary=await api(`/solicitacoes/${r.id}/pagamento`);assert.equal(summary.status,200);assert.equal(summary.data.total,108.5);assert.equal(summary.data.subtotal,105);assert.equal(summary.data.taxa_servico,3.5);assert.equal(summary.data.dias,3);const {paymentDeadline}=await import("../../app/services/paymentRules.ts");const expected=Math.floor((paymentDeadline(r).getTime()-Date.now())/1000);assert.ok(Math.abs(summary.data.prazo_restante_segundos-expected)<=2);assert.ok(summary.data.prazo_restante_segundos>86400);await prisma.itens.update({where:{id:r.item_id},data:{preco_por_dia:90}});assert.equal((await api(`/solicitacoes/${r.id}/pagamento`)).data.total,108.5);});
 await t.test("aprovação grava fim da retirada para datas futuras e para hoje",async()=>{const {paymentDeadline}=await import("../../app/services/paymentRules.ts");const parts=Object.fromEntries(new Intl.DateTimeFormat("en-US",{timeZone:"America/Sao_Paulo",year:"numeric",month:"2-digit",day:"2-digit"}).formatToParts(new Date()).map(p=>[p.type,p.value]));const localToday=new Date(`${parts.year}-${parts.month}-${parts.day}T00:00:00.000Z`);for(const pickup of [start,localToday]){const r=await rental({status:"pendente",data_inicio:pickup,data_fim:new Date(pickup.getTime()+86400000),expira_em:new Date(Date.now()+3600000),pagamento_ate:null});const response=await api(`/solicitacoes/${r.id}`,"PATCH",{status:"aprovado"},owner);assert.equal(response.status,200,JSON.stringify(response.data));const stored=await prisma.alugueis.findUniqueOrThrow({where:{id:r.id}});assert.equal(stored.pagamento_ate?.toISOString(),paymentDeadline(stored).toISOString());}});
 await t.test("confirmação exige pagamento efetivo e usa valor histórico, sem confiar na URL",async()=>{const r=await rental();const path=`/solicitacoes/${r.id}/confirmacao-pagamento`;const missing=await api(`/solicitacoes/${crypto.randomUUID()}/confirmacao-pagamento`);assert.equal(missing.status,404);assert.equal(missing.data.codigo,"nao_encontrada");assert.equal(missing.data.success,false);assert.equal(missing.data.message,missing.data.mensagem);const forbidden=await api(path,"GET",undefined,other);assert.equal(forbidden.status,403);assert.equal(forbidden.data.codigo,"nao_pertence");const ownerResult=await api(path,"GET",undefined,owner);assert.equal(ownerResult.status,403);for(const status of [null,"pendente","falhou","expirado"]){if(status)await prisma.pagamentos.create({data:{aluguel_id:r.id,tipo:"aluguel",valor:108.5,metodo:"pix",status,gateway:"demo"}});const result=await api(path);assert.equal(result.status,409);assert.equal(result.data.codigo,"nao_paga");assert.equal(result.data.message,result.data.mensagem);if(status)await prisma.pagamentos.deleteMany({where:{aluguel_id:r.id}});}const p=await prisma.pagamentos.create({data:{aluguel_id:r.id,tipo:"aluguel",valor:108.5,metodo:"cartao",status:"pago",gateway:"demo"}});await prisma.alugueis.update({where:{id:r.id},data:{status:"pago"}});await prisma.itens.update({where:{id:r.item_id},data:{preco_por_dia:999,titulo:"Título alterado"}});const expected={produto:{id:r.item_id,titulo:"Título alterado"},data_retirada:r.data_inicio.toISOString().slice(0,10),data_devolucao:r.data_fim.toISOString().slice(0,10),dias:3,total_pago:108.5};const success=await api(path);assert.equal(success.status,200);assert.deepEqual(success.data,expected);assert.deepEqual((await api(`${path}?total_pago=1&dias=999&data_retirada=2000-01-01&titulo=forjado`)).data,expected);assert.equal(Number((await prisma.pagamentos.findUniqueOrThrow({where:{id:p.id}})).valor),108.5);});
 let pixId="",pixReference="",pixRental="";
 await t.test("PIX real pelo adapter fake calcula valor somente no backend",async()=>{const r=await rental();pixRental=r.id;const response=await charge(r.id,{metodo:"pix",total:1,valor_total:1,usuario_id:other.id,cpf:other.cpf,device_id:"device-test"});assert.equal(response.status,200,JSON.stringify(response.data));assert.equal(response.data.status,"pendente");assert.equal(response.data.valor_total,108.5);assert.match(response.data.pix.copia_e_cola,/^PIX-real/);assert.equal(response.data.pix.qr_code_base64,"aW1hZ2U=");pixId=response.data.pagamento_id;pixReference=(await prisma.pagamentos.findUniqueOrThrow({where:{id:pixId}})).referencia!;assert.equal(response.data.ambiente,"mercado_pago");});
 await t.test("consulta de status usa adapter público",async()=>{const response=await api(`/pagamentos/${pixId}`);assert.equal(response.data.status,"pendente");assert.equal(response.data.status_interno,"pendente");});
 await t.test("pagamento de outro usuário retorna 403",async()=>{assert.equal((await api(`/pagamentos/${pixId}`,"GET",undefined,other)).status,403);assert.equal((await api(`/solicitacoes/${pixRental}/pagamento`,"GET",undefined,other)).status,403);});
 await t.test("pagador autorizado e locador/admin bloqueados na rota pública",async()=>{assert.equal((await api(`/pagamentos/${pixId}`)).status,200);assert.equal((await api(`/pagamentos/${pixId}`,"GET",undefined,owner)).status,403);const admin=await prisma.usuarios.create({data:{nome:"Admin",cpf:cpf(),email:`mp-admin-${crypto.randomUUID()}@test.local`,senha_hash:"not-used",tipo:"admin"}});assert.equal((await api(`/pagamentos/${pixId}`,"GET",undefined,admin)).status,403);assert.equal((await api(`/admin/pagamentos/${pixId}`,"GET",undefined,admin)).status,200);});
 await t.test("aluguel e exportação não entregam PIX ou payload do provedor ao locador",async()=>{
  const payment=await prisma.pagamentos.findUniqueOrThrow({where:{id:pixId}});
  await prisma.pagamentos.update({where:{id:pixId},data:{dados:{...(payment.dados as object),provider_secret:"never-export"}}});
  for(const path of [`/alugueis/${pixRental}`,`/solicitacoes/${pixRental}`,`/pedidos/${pixRental}`]){
   const result=await api(path,"GET",undefined,owner);assert.equal(result.status,200);
   const body=JSON.stringify(result.data);for(const secret of ["codigo_copia_cola","qr_code_base64","provider_status","provider_secret","PIX-real"])assert.ok(!body.includes(secret),`${path}: ${secret}`);
  }
  const exportResult=await api("/usuarios/me/exportar","GET",undefined,owner);assert.equal(exportResult.status,200);
  for(const secret of ["codigo_copia_cola","qr_code_base64","provider_secret","never-export"])assert.ok(!JSON.stringify(exportResult.data).includes(secret),secret);
  assert.equal((await api(`/pagamentos/${pixId}`)).status,200);
 });
 await t.test("Idempotency-Key obrigatório e UUID válido",async()=>{const r=await rental();assert.equal((await api(`/solicitacoes/${r.id}/pagamentos`,"POST",{metodo:"pix"})).status,422);assert.equal((await charge(r.id,{metodo:"pix"},"invalid")).status,422);});
 await t.test("PIX repetido não duplica mesmo com novas chaves",async()=>{const before=paymentCreates,key=crypto.randomUUID();const first=await charge(pixRental,{metodo:"pix"},key),second=await charge(pixRental,{metodo:"pix"},key);assert.equal(first.data.pagamento_id,pixId);assert.equal(second.data.pagamento_id,pixId);assert.equal(paymentCreates,before);});
 await t.test("mesma chave rejeita device diferente, método, cartão e token diferentes",async()=>{const r=await rental(),key=crypto.randomUUID();assert.equal((await charge(r.id,{metodo:"pix",device_id:"device-a"},key)).status,200);const changed=await charge(r.id,{metodo:"pix",device_id:"device-b"},key);assert.equal(changed.status,409);assert.equal(changed.data.codigo,"idempotencia_conflitante");const cardRental=await rental(),cardKey=crypto.randomUUID();const body={metodo:"cartao",token_cartao:"challenge-token",payment_method_id:"visa"};assert.equal((await charge(cardRental.id,body,cardKey)).status,200);for(const incompatible of [{...body,payment_method_id:"master"},{...body,token_cartao:"other-token"},{...body,cartao_id:cardA}]){const answer=await charge(cardRental.id,incompatible,cardKey);assert.equal(answer.status,409);assert.equal(answer.data.codigo,"idempotencia_conflitante");}});
 await t.test("mesma chave em solicitações diferentes é conflito",async()=>{const a=await rental(),b=await rental(),key=crypto.randomUUID();const left=await charge(a.id,{metodo:"pix"},key),right=await charge(b.id,{metodo:"pix"},key);assert.equal(left.status,200);assert.equal(right.status,409);assert.equal(right.data.codigo,"idempotencia_conflitante");assert.equal(await prisma.pagamentos.count({where:{aluguel_id:b.id}}),0);});
 // Exercita a chave idempotente contra duas tentativas que chegam ao mesmo tempo.
 await t.test("requests concorrentes com mesma chave não cobram duas vezes",async()=>{const r=await rental(),key=crypto.randomUUID(),before=paymentCreates;const responses=await Promise.all([charge(r.id,{metodo:"pix"},key),charge(r.id,{metodo:"pix"},key)]);assert.ok(responses.every(r=>r.status===200),JSON.stringify(responses));assert.equal(responses[0]!.data.pagamento_id,responses[1]!.data.pagamento_id);assert.equal(paymentCreates,before+1);});
 await t.test("HTTP externo espera após commit e libera o lock do aluguel",async()=>{const r=await rental();let release!:()=>void;externalPause=new Promise<void>(resolve=>{release=resolve;});const pending=charge(r.id);try{for(let attempts=0;attempts<40;attempts++){if(await prisma.pagamentos.count({where:{aluguel_id:r.id}}))break;await new Promise(resolve=>setTimeout(resolve,25));}assert.equal(await prisma.pagamentos.count({where:{aluguel_id:r.id}}),1);await prisma.$transaction(async tx=>{await tx.$executeRaw`SET LOCAL lock_timeout = '200ms'`;await tx.$queryRaw`SELECT id FROM alugueis WHERE id=${r.id}::uuid FOR UPDATE`;});}finally{release();externalPause=null;}assert.equal((await pending).status,200);});
 await t.test("PIX → cartão cancela anterior antes de criar",async()=>{const before=cancels;const response=await charge(pixRental,{metodo:"cartao",token_cartao:"approved-token",cartao_id:cardA});assert.equal(response.status,200,JSON.stringify(response.data));assert.equal(response.data.status,"aprovado");assert.equal(cancels,before+1);assert.equal((await prisma.pagamentos.findUniqueOrThrow({where:{id:pixId}})).status,"cancelado");});
 await t.test("cartão aprovado e repetição idempotente após aluguel pago",async()=>{const r=await rental(),key=crypto.randomUUID(),before=paymentCreates;const body={metodo:"cartao",token_cartao:"approved-token",payment_method_id:"visa"};const first=await charge(r.id,body,key),second=await charge(r.id,body,key);assert.equal(first.status,200);assert.equal(first.data.status,"aprovado");assert.equal(first.data.pagamento_id,second.data.pagamento_id);assert.equal(paymentCreates,before+1);assert.equal((await prisma.alugueis.findUniqueOrThrow({where:{id:r.id}})).status,"pago");});
 await t.test("cartão recusado retorna HTTP 200 + recusado",async()=>{const r=await rental(),response=await charge(r.id,{metodo:"cartao",token_cartao:"rejected-token",payment_method_id:"visa"});assert.equal(response.status,200);assert.equal(response.data.status,"recusado");assert.ok(response.data.mensagem);assert.equal((await prisma.alugueis.findUniqueOrThrow({where:{id:r.id}})).status,"aprovado");});
 await t.test("aprovação síncrona MP não confirma sem webhook",async()=>{
  autoCardWebhook=false;
  try{const r=await rental(),response=await charge(r.id,{metodo:"cartao",token_cartao:"approved-token",payment_method_id:"visa"});assert.equal(response.status,200);assert.equal(response.data.status,"pendente");assert.equal((await prisma.alugueis.findUniqueOrThrow({where:{id:r.id}})).status,"aprovado");const p=await prisma.pagamentos.findUniqueOrThrow({where:{id:response.data.pagamento_id}});assert.equal(p.status,"pendente");assert.equal((await api(`/pagamentos/${p.id}`)).data.status,"pendente");assert.equal((await webhook(p.referencia!)).status,200);assert.equal((await api(`/pagamentos/${p.id}`)).data.status,"aprovado");}finally{autoCardWebhook=true;}
 });
 await t.test("3DS encaminha desafio e mantém pagamento pendente",async()=>{
  const r=await rental(),response=await charge(r.id,{metodo:"cartao",token_cartao:"challenge-token",payment_method_id:"visa"});assert.equal(response.status,200);assert.equal(response.data.status,"pendente");assert.deepEqual(response.data.acao_necessaria,{tipo:"3ds",url:"https://issuer.test/challenge",creq:"challenge-request"});
  const p=await prisma.pagamentos.findUniqueOrThrow({where:{id:response.data.pagamento_id}});payments.get(p.referencia!).status="approved";assert.equal((await webhook(p.referencia!)).status,200);assert.equal((await api(`/pagamentos/${p.id}`)).data.acao_necessaria,undefined);
 });
 await t.test("timeout após criação é recuperado pelo job sem cobrança duplicada",async()=>{
  const r=await rental(),before=paymentCreates;loseCreationResponse=true;const response=await charge(r.id);assert.equal(response.status,502);const p=await prisma.pagamentos.findFirstOrThrow({where:{aluguel_id:r.id}});assert.equal(p.referencia,null);assert.equal(paymentCreates,before+1);
  const past=new Date(new Date(Date.now()-2*86400000).toISOString().slice(0,10));await prisma.alugueis.update({where:{id:r.id},data:{data_inicio:past,data_fim:past}});const {maintainRentals}=await import("../../app/services/rentalMaintenance.ts");await maintainRentals(true);const recovered=await prisma.pagamentos.findUniqueOrThrow({where:{id:p.id}});assert.ok(recovered.referencia);assert.equal(recovered.status,"cancelado");assert.equal(paymentCreates,before+1);
 });
 await t.test("PIX sem QR, código ou expiração exige conciliação e não oferece sucesso",async()=>{for(const missing of ["qr","code","expiration","partial"]){const r=await rental();pixResponseMissing=missing;const response=await charge(r.id);assert.equal(response.status,502,JSON.stringify(response.data));assert.equal(response.data.codigo,"pix_incompleto");const payment=await prisma.pagamentos.findFirstOrThrow({where:{aluguel_id:r.id}});assert.equal(payment.status,"conciliacao");assert.equal((await api(`/pagamentos/${payment.id}`)).status,409);assert.equal(await prisma.conciliacoes_pagamento.count({where:{pagamento_id:payment.id,status:"aberta"}}),1);}});
 await t.test("dois workers não cancelam a mesma cobrança externa simultaneamente",async()=>{const r=await rental(),created=await charge(r.id),payment=await prisma.pagamentos.findUniqueOrThrow({where:{id:created.data.pagamento_id}});let release!:()=>void;externalPause=new Promise<void>(resolve=>{release=resolve;});const before=cancels,first=api(`/pagamentos/${payment.id}/cancelar`,"POST",{});await new Promise(resolve=>setTimeout(resolve,100));const second=api(`/pagamentos/${payment.id}/cancelar`,"POST",{});release();const results=await Promise.all([first,second]);externalPause=null;assert.ok(results.every(result=>[200,202].includes(result.status)),JSON.stringify(results));assert.equal(cancels,before+1);});
 await t.test("dois workers não estornam a mesma cobrança externa simultaneamente",async()=>{const r=await rental(),created=await charge(r.id,{metodo:"cartao",token_cartao:"approved-token",payment_method_id:"visa"}),payment=await prisma.pagamentos.findUniqueOrThrow({where:{id:created.data.pagamento_id}});let release!:()=>void;externalPause=new Promise<void>(resolve=>{release=resolve;});const before=refundCalls,first=api(`/pagamentos/${payment.id}/estornar`,"POST",{});await new Promise(resolve=>setTimeout(resolve,100));const second=api(`/pagamentos/${payment.id}/estornar`,"POST",{});release();const results=await Promise.all([first,second]);externalPause=null;assert.ok(results.every(result=>[200,202].includes(result.status)),JSON.stringify(results));assert.equal(refundCalls,before+1);assert.equal(await prisma.eventos_aluguel.count({where:{aluguel_id:r.id,motivo:"Pagamento estornado"}}),1);});
 await t.test("PIX expirado com nova operação cancela anterior antes de recriar",async()=>{
  const r=await rental(),first=await charge(r.id),p=await prisma.pagamentos.findUniqueOrThrow({where:{id:first.data.pagamento_id}});const details=p.dados as any;await prisma.pagamentos.update({where:{id:p.id},data:{dados:{...details,expira_em:new Date(Date.now()-1000).toISOString()}}});assert.equal((await api(`/pagamentos/${p.id}`)).data.status,"expirado");const before=cancels,next=await charge(r.id);assert.equal(next.status,200);assert.notEqual(next.data.pagamento_id,p.id);assert.equal(cancels,before+1);
 });
 await t.test("nova chave com cartão pendente retorna ja_paga",async()=>{
  const r=await rental(),body={metodo:"cartao",token_cartao:"challenge-token",payment_method_id:"visa"};assert.equal((await charge(r.id,body)).status,200);const second=await charge(r.id,body);assert.equal(second.status,409);assert.equal(second.data.codigo,"ja_paga");
 });
 await t.test("token de cartão não é persistido",async()=>{const rows=await prisma.pagamentos.findMany({where:{alugueis:{locatario_id:renter.id}}});const serialized=JSON.stringify(rows);for(const token of["approved-token","rejected-token","save-token"])assert.ok(!serialized.includes(token));assert.ok(!JSON.stringify(await prisma.cartoes.findMany()).includes("save-token"));});
 await t.test("PAN e CVV rejeitados",async()=>{const r=await rental();assert.equal((await charge(r.id,{metodo:"cartao",token_cartao:"token",payment_method_id:"visa",cvv:"123"})).status,422);assert.equal((await api("/cartoes","POST",{token_cartao:"token",card_number:"4242424242424242"})).status,422);});
 await t.test("webhook inválido não modifica banco",async()=>{assert.equal((await webhook(pixReference,undefined,false)).status,401);});
 await t.test("webhook antigo e futuro são rejeitados mesmo com HMAC válido",async()=>{for(const timestamp of [Math.floor(Date.now()/1000)-301,Math.floor(Date.now()/1000)+301])assert.equal((await webhook(pixReference,undefined,true,timestamp)).status,401);});
 // A segunda entrega do evento deve preservar o pagamento e evitar avisos repetidos.
 await t.test("webhook duplicado confirma e notifica uma vez",async()=>{const r=await rental(),created=await charge(r.id),p=await prisma.pagamentos.findUniqueOrThrow({where:{id:created.data.pagamento_id}}),ref=p.referencia!;payments.get(ref).status="approved";const event=String(++seq);assert.equal((await webhook(ref,event)).status,200);const count=await prisma.notificacoes.count({where:{tipo:"pagamento",contexto:{path:["pagamentoId"],equals:p.id}}});assert.equal((await webhook(ref,event)).status,200);assert.equal(await prisma.notificacoes.count({where:{tipo:"pagamento",contexto:{path:["pagamentoId"],equals:p.id}}}),count);assert.equal(count,2);assert.equal((await api(`/pagamentos/${p.id}`)).data.status,"aprovado");});
 await t.test("webhook antecipado fica na inbox e é reconciliado",async()=>{earlyWebhook=true;const r=await rental(),response=await charge(r.id);assert.equal(response.status,200);const p=await prisma.pagamentos.findUniqueOrThrow({where:{id:response.data.pagamento_id}});const events=await prisma.webhook_eventos.findMany({where:{payload:{path:["resourceId"],equals:p.referencia!}}});assert.ok(events.length);assert.ok(events.every(e=>e.processado_em));});
 await t.test("valor divergente no webhook gera análise sem pagar",async()=>{const r=await rental(),response=await charge(r.id),p=await prisma.pagamentos.findUniqueOrThrow({where:{id:response.data.pagamento_id}});payments.get(p.referencia!).transaction_amount=1;payments.get(p.referencia!).status="approved";assert.equal((await webhook(p.referencia!)).status,422);assert.equal((await prisma.pagamentos.findUniqueOrThrow({where:{id:p.id}})).status,"pendente");assert.equal(await prisma.conciliacoes_pagamento.count({where:{pagamento_id:p.id}}),1);});
 await t.test("job ignora antigo corte de 24h e cancela somente após retirada",async()=>{const future=await rental({pagamento_ate:new Date(Date.now()-1000)});await (await import("../../app/services/rentalMaintenance.ts")).maintainRentals();assert.equal((await prisma.alugueis.findUniqueOrThrow({where:{id:future.id}})).status,"aprovado");const past=new Date(new Date(Date.now()-2*86400000).toISOString().slice(0,10)),r=await rental({data_inicio:past,data_fim:past,pagamento_ate:new Date(Date.now()+86400000)}),response=await charge(r.id);assert.equal(response.status,409);assert.equal(response.data.codigo,"cancelada");assert.equal((await prisma.alugueis.findUniqueOrThrow({where:{id:r.id}})).status,"cancelado");assert.equal(await prisma.pagamentos.count({where:{aluguel_id:r.id}}),0);});
 await t.test("objeto indisponível é revalidado antes de pagar",async()=>{const r=await rental();await prisma.itens.update({where:{id:r.item_id},data:{disponivel:false}});const response=await charge(r.id);assert.equal(response.status,409);assert.equal(response.data.codigo,"objeto_indisponivel");});
 await t.test("job cancela todos os vencidos além de 100 sem duplicar",async()=>{const past=new Date(new Date(Date.now()-2*86400000).toISOString().slice(0,10));const ids:string[]=[];for(let i=0;i<105;i++)ids.push((await rental({data_inicio:past,data_fim:past,pagamento_ate:new Date(Date.now()+86400000)})).id);const {maintainRentals}=await import("../../app/services/rentalMaintenance.ts");await maintainRentals();assert.equal(await prisma.alugueis.count({where:{id:{in:ids},status:"aprovado"}}),0);assert.equal(await prisma.alugueis.count({where:{id:{in:ids},status:"cancelado"}}),105);const count=await prisma.eventos_aluguel.count({where:{motivo:"Prazo de pagamento expirado"}});await maintainRentals();assert.equal(await prisma.eventos_aluguel.count({where:{motivo:"Prazo de pagamento expirado"}}),count);});
 await t.test("gateway demo não afeta pagamento real",async()=>{env.PAYMENT_MODE="demo";try{assert.equal((await api(`/pagamentos/${pixId}/simular`,"POST",{status:"pago"})).status,403);assert.equal((await api("/pagamentos/pix/confirmar","POST",{aluguel_id:pixRental})).status,409);}finally{env.PAYMENT_MODE="gateway";}});
 await t.test("estorno pendente bloqueia retirada e é idempotente",async()=>{const r=await rental(),response=await charge(r.id,{metodo:"cartao",token_cartao:"approved-token",payment_method_id:"visa"}),id=response.data.pagamento_id;refundPending=true;const refund=await api(`/pagamentos/${id}/estornar`,"POST",{});assert.equal(refund.status,202);assert.equal((await prisma.pagamentos.findUniqueOrThrow({where:{id}})).status,"estorno_pendente");const form=new FormData();form.append("fotos",new Blob([Buffer.from("iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+ip1sAAAAASUVORK5CYII=","base64")],{type:"image/png"}),"photo.png");const blocked=await fetch(`${base}/retiradas/${r.id}/fotos`,{method:"POST",headers:{Authorization:`Bearer ${bearer(renter)}`},body:form});assert.equal(blocked.status,409);assert.match((await blocked.json() as any).message,/financeira/);const {requestFinancial}=await import("../../app/controllers/paymentsController.ts");assert.equal((await requestFinancial(id,"refund")).status,"estorno_pendente");refundPending=false;await requestFinancial(id,"refund");await requestFinancial(id,"refund");assert.equal(await prisma.eventos_aluguel.count({where:{aluguel_id:r.id,motivo:"Pagamento estornado"}}),1);});
 await t.test("multa explicitamente desabilitada retorna erro controlado",async()=>{process.env.MULTA_VALOR_DIA="";try{const past=new Date(new Date(Date.now()-3*86400000).toISOString().slice(0,10)),r=await rental({data_inicio:past,data_fim:past,status:"retirado"});assert.equal((await api(`/solicitacoes/${r.id}/multa`)).data.codigo,"multa_desabilitada");}finally{delete process.env.MULTA_VALOR_DIA;}});
 await t.test("multa congelada usa gateway e webhook sem alterar ciclo do aluguel",async()=>{process.env.MULTA_VALOR_DIA="10";try{const past=new Date(new Date(Date.now()-2*86400000).toISOString().slice(0,10)),r=await rental({data_inicio:past,data_fim:past,status:"devolvido"});const summary=await api(`/solicitacoes/${r.id}/multa`);assert.equal(summary.data.valor_total,20);const response=await api(`/solicitacoes/${r.id}/multa/pagamentos`,"POST",{metodo:"pix",valor_total:1},renter,crypto.randomUUID());assert.equal(response.status,200,JSON.stringify(response.data));assert.equal(response.data.valor_total,20);const p=await prisma.pagamentos.findUniqueOrThrow({where:{id:response.data.pagamento_id}});assert.equal(p.tipo,"multa");payments.get(p.referencia!).status="approved";assert.equal((await webhook(p.referencia!)).status,200);assert.equal((await prisma.alugueis.findUniqueOrThrow({where:{id:r.id}})).status,"devolvido");assert.equal((await api(`/solicitacoes/${r.id}/multa`)).data.status,"paga");}finally{delete process.env.MULTA_VALOR_DIA;}});
 // Garante que falhas antigas nos primeiros 100 registros não impedem lotes seguintes.
 await t.test("PIX 101º avança após 100 falhas antigas",async()=>{
  const validRental=await rental(),response=await charge(validRental.id),validId=response.data.pagamento_id;
  await prisma.pagamentos.update({where:{id:validId},data:{status:"conciliacao",dados:{}}});
  const itemRows=Array.from({length:100},()=>({id:crypto.randomUUID(),usuario_id:owner.id,titulo:"Fila PIX",preco_por_dia:1,valor_mercado:30}));
  await prisma.itens.createMany({data:itemRows});
  const rentalRows=itemRows.map(item=>({id:crypto.randomUUID(),item_id:item.id,locador_id:owner.id,locatario_id:renter.id,data_inicio:start,data_fim:end,valor_total:1,status:"aprovado"}));
  await prisma.alugueis.createMany({data:rentalRows});
  const badIds=rentalRows.map((row,i)=>({id:crypto.randomUUID(),aluguel_id:row.id,valor:1,metodo:"pix",status:"conciliacao",gateway:"mercado_pago",referencia:String(800000000+i),criado_em:new Date("2026-01-01") }));
  await prisma.pagamentos.createMany({data:badIds});
  const {reconcileIncompletePayments}=await import("../../app/controllers/paymentsController.ts");
  await reconcileIncompletePayments();
  assert.equal((await prisma.pagamentos.findUniqueOrThrow({where:{id:validId}})).status,"conciliacao");
  await Promise.all([reconcileIncompletePayments(),reconcileIncompletePayments()]);
  assert.equal((await prisma.pagamentos.findUniqueOrThrow({where:{id:validId}})).status,"pendente");
  assert.equal((await prisma.pagamentos.findUniqueOrThrow({where:{id:validId}})).conciliacao_tentativas,1);
  await prisma.pagamentos.deleteMany({where:{id:{in:badIds.map(row=>row.id)}}});
 });
 await t.test("cartão 101º avança após 100 falhas antigas",async()=>{
  await prisma.operacoes_gateway.updateMany({where:{tipo:"cartao_excluir",estado:{in:["pendente","falhou"]}},data:{proxima_tentativa_em:new Date(Date.now()+86400000)}});
  const busy=await prisma.cartoes.create({data:{id:`busy-${crypto.randomUUID()}`,usuario_id:renter.id,customer_id:"customer-queue",gateway:"mercado_pago",payment_method_id:"visa",bandeira:"Visa",ultimos_digitos:"4242",validade:"12/29"}});
  const rentalRow=await rental();await prisma.pagamentos.create({data:{aluguel_id:rentalRow.id,valor:10,metodo:"cartao",status:"pendente",gateway:"mercado_pago",cartao_id:busy.id}});
  const good=await prisma.cartoes.create({data:{id:`good-${crypto.randomUUID()}`,usuario_id:renter.id,customer_id:"customer-queue",gateway:"mercado_pago",payment_method_id:"visa",bandeira:"Visa",ultimos_digitos:"4242",validade:"12/29"}});
  const bad=Array.from({length:100},()=>({chave:`queue-bad-${crypto.randomUUID()}`,tipo:"cartao_excluir",usuario_id:renter.id,fingerprint:"queue",estado:"falhou",referencia:busy.id,dados:{customer_id:"customer-queue",gateway:"mercado_pago"},criado_em:new Date("2026-01-01")}));
  await prisma.operacoes_gateway.createMany({data:bad});
  const goodKey=`queue-good-${crypto.randomUUID()}`;await prisma.operacoes_gateway.create({data:{chave:goodKey,tipo:"cartao_excluir",usuario_id:renter.id,fingerprint:"queue",estado:"falhou",referencia:good.id,dados:{customer_id:"customer-queue",gateway:"mercado_pago"}}});
  const {reconcileCardOperations}=await import("../../app/controllers/cardsController.ts");
  await reconcileCardOperations();assert.notEqual((await prisma.operacoes_gateway.findUniqueOrThrow({where:{chave:goodKey}})).estado,"concluida");
  await Promise.all([reconcileCardOperations(),reconcileCardOperations()]);
  assert.equal((await prisma.operacoes_gateway.findUniqueOrThrow({where:{chave:goodKey}})).estado,"concluida");
  assert.equal(await prisma.cartoes.findUnique({where:{id:good.id}}),null);
  await prisma.operacoes_gateway.deleteMany({where:{chave:{in:bad.map(row=>row.chave)}}});
 });
 await t.test("webhook 101º avança em lote sob dois workers",async()=>{
  await prisma.webhook_eventos.updateMany({where:{processado_em:null},data:{proxima_tentativa_em:new Date(Date.now()+86400000)}});
  const rentalRow=await rental(),response=await charge(rentalRow.id),payment=await prisma.pagamentos.findUniqueOrThrow({where:{id:response.data.pagamento_id}});
  const bad=Array.from({length:100},()=>({id:`queue-invalid-${crypto.randomUUID()}`,payload:{invalid:true},criado_em:new Date("2026-01-01")}));await prisma.webhook_eventos.createMany({data:bad});
  const eventId=`mp:queue-${crypto.randomUUID()}`;await prisma.webhook_eventos.create({data:{id:eventId,payload:{provider:"mercado_pago",resourceId:payment.referencia}}});
  const {reconcilePaymentWebhooks}=await import("../../app/controllers/paymentsController.ts");
  await reconcilePaymentWebhooks();assert.equal((await prisma.webhook_eventos.findUniqueOrThrow({where:{id:eventId}})).processado_em,null);
  await Promise.all([reconcilePaymentWebhooks(),reconcilePaymentWebhooks()]);
  const event=await prisma.webhook_eventos.findUniqueOrThrow({where:{id:eventId}});assert.ok(event.processado_em);assert.equal(event.tentativas,1);
  await prisma.webhook_eventos.deleteMany({where:{id:{in:bad.map(row=>row.id)}}});
 });
});
